# ä¿¡æ¯
info:
  # é¦–é¡µå¤§æ ‡é¢˜ï¼ˆfalseã€defaultã€valueï¼›å…³é—­ã€é»˜è®¤ã€å€¼ã€‚ï¼‰
  big_title: default
  # é¦–é¡µå‰¯æ ‡é¢˜ï¼ˆfalseã€defaultã€valueï¼›å…³é—­ã€é»˜è®¤ã€å€¼ã€‚ï¼‰
  subtitle: hello world
  # ç«™ç‚¹å›¾æ ‡
  favicon: '/favicon.png'
  # å¤´åƒï¼ˆé»˜è®¤ä½¿ç”¨ç«™ç‚¹å›¾æ ‡ï¼‰
  avatar: '/avatar.png'
  # ç¤¾äº¤é“¾æ¥
  social_link:
    - fab fa-github, https://github.com/JonnyJong, Github
  # å»ºç«™æ—¶é—´
  site_begin: 2020-08-10 07:00:00

# =============================================================
# å¿«æ·å…¥å£ï¼ˆé¦–é¡µæ ‡é¢˜æ—ï¼‰
# åªåˆ¶ä½œåŸºæœ¬çš„æ¡†æ¶ï¼Œç­‰å¾…åˆ¶ä½œå„ç§é£æ ¼çš„æ¨¡æ¿æ’ä»¶ã€‚æ•…æš‚æ—¶åœå·¥
quick_entrance:
  # æ˜¯å¦å¼€å¯ï¼ˆtrue/falseï¼‰
  enable: false
  # ç»„ä»¶ï¼ˆä¸å»ºè®®è®¾ç½®è¿‡å¤šçš„ç»„ä»¶ï¼‰
  items:
      # ç»„ä»¶ idï¼ˆä½œç”¨äºé¡µé¢æ’ç‰ˆã€ä¸å¯è§ï¼‰
    - id: 
      # è‡ªå®šä¹‰ html + cssï¼ˆå¼€å¯åä¸‹åˆ—é€‰é¡¹é™¤ content å¤–å‡æ— æ•ˆï¼‰
      custom:
      # ç»„ä»¶å
      name: 
      # é“¾æ¥
      url: 
      # æ ·å¼ï¼ˆçªèµ·ï¼šä¸‹å›¾ä¸Šæ–‡èƒŒæ™¯ã€ä¸Šå›¾ä¸‹æ–‡èƒŒæ™¯ã€å·¦ä¸Šå›¾ä¸Šæ–‡èƒŒæ™¯å†…å®¹ï¼›å‡¹ä¸‹ï¼šä¸‹å›¾ä¸Šæ–‡èƒŒæ™¯ã€ä¸Šå›¾ä¸‹æ–‡èƒŒæ™¯ã€å·¦ä¸Šå›¾ä¸Šæ–‡èƒŒæ™¯å†…å®¹ï¼‰ 
      # æš‚æ—¶ä¸å¯ç”¨ï¼šç”±é£æ ¼æ’ä»¶å†³å®š
      # style: 
      # ç±»å‹
      type:
      # å°ºå¯¸ï¼ˆ1x1ã€1x2ã€2x2ï¼‰
      size: 
      # å›¾æ ‡
      img: 
      # èƒŒæ™¯å›¾ç‰‡
      background_img: 
      # é¢œè‰²
      color:
      # å†…å®¹ï¼ˆæ”¯æŒ html + cssï¼‰
      content: 

# =============================================================
# å½’æ¡£
archive:
  # é¡µé¢ä»…å±•ç¤ºå½’æ¡£ï¼ˆå¼€å¯åå½’æ¡£é¡µçš„å±•ç¤ºæ–¹å¼å°†æ”¹å˜ï¼Œä¸” show å¤±æ•ˆï¼‰ï¼ˆæœªé…ç½®ï¼‰
  only_archive: 
  # å½’æ¡£é¡µå±•ç¤ºï¼ˆä½ å¯ä»¥å°†å½’æ¡£ã€å½’ç±»ã€æ ‡ç­¾å…¨éƒ¨é›†ä¸­åˆ°è¿™ä¸ªé¡µé¢æ¥æ˜¾ç¤ºï¼Œä½ å¯ä»¥è‡ªå®šä¹‰å±•ç¤ºé¡ºåºï¼Œæœ€å°‘éœ€è¦å±•ç¤ºä¸€é¡¹ï¼‰
  show:
    - tag
    - category
    - archive
  # æ˜¾ç¤ºæ•°é‡
  show_count: true
  # æ˜¾ç¤ºæ€»æ•°
  show_total: true
  # æŒ‰æœˆä»½
  monthly: true
  # æ—¥æœŸæ ¼å¼ï¼ˆé»˜è®¤ï¼šYYYY MMMMï¼‰
  format:
  # å°é¢å›¾
  cover: /448.jpg
# åˆ†ç±»
category:
  # æ˜¾ç¤ºæ•°é‡
  show_count: true
  # æ˜¾ç¤ºæ€»æ•°
  show_total: true
  # å°†å†…å®¹æ¸²æŸ“åˆ°åˆ†ç±»ä¹‹å
  after_content: true
# æ ‡ç­¾
tag:
  # æ˜¾ç¤ºæ•°é‡
  show_count: true
  # æ˜¾ç¤ºæ€»æ•°
  show_total: true
  # å°†å†…å®¹æ¸²æŸ“åˆ°æ ‡ç­¾ä¹‹å
  after_content: true

# =============================================================
# è‡ªå®šä¹‰å¤–è§‚
custom:
  # å¯¼èˆªæ 
  navbar:
    # è‡ªå®šä¹‰ç»„ä»¶ï¼ˆå…è®¸è‡ªç”±è°ƒæ•´é¡ºåºï¼‰
    items:
      mbl, side_nav_btn:
      al, site, 0: /logo.png, default, root
      pc, img, 0: /logo.png, /
      pc, text, 0: hello world!, /
      al, act_statistics:
        archive: /archives/
        categorie: /categories/
        tag: /tags/
      al, hr:
      pc, placeholder, 0: 
      al, menu, ä¸»é¡µ, fas fa-home, /:
      mbl, menu, å…³äº, fa fa-heart, /about/:
      al, menu, å‹æƒ…é“¾æ¥, fa fa-link, /link/:
      # æ­¤å¤„æœ‰bugï¼Œå¦‚æœ none æ¢æˆé“¾æ¥ï¼Œä¼šå‡ºç°å¥‡æ€ªçš„å±‚æ¬¡æ¸²æŸ“é”™è¯¯
      al, menu, æ–‡ç« , fa fa-graduation-cap, /hello/:
        æ ‡ç­¾: /tags/, fa fa-tags
        å½’ç±»: /categories/, fa fa-archive
        å½’æ¡£: /archives/, fa fa-folder-open
    # æ‰‹æœºç«¯é¡¶æ ç»„ä»¶ï¼ˆæ–¹æ³•åŒä¸Šï¼Œäº’ç›¸ç‹¬ç«‹ï¼‰
    mbl_item_on_navbar:
      al, side_nav_btn:
      al, placeholder, 0: 
      al, site, 0: /logo.png, default, root
      al, placeholder, 1: 
    
    # å¯¼èˆªæ é«˜åº¦ï¼ˆé»˜è®¤ 60pxï¼‰
    height: 
    # å¯¼èˆªæ å¤–éƒ¨å®½åº¦ï¼ˆé»˜è®¤ 100%ï¼‰
    outer_width:
    # å¯¼èˆªæ å¤–éƒ¨æœ€å¤§å®½åº¦ ï¼ˆé»˜è®¤ 100%ï¼‰
    outer_max_width:
    # å¯¼èˆªæ å†…éƒ¨å®½åº¦ ï¼ˆé»˜è®¤ 90%ï¼‰
    inner_width: 
    # å¯¼èˆªæ å†…éƒ¨æœ€å¤§å®½åº¦ ï¼ˆé»˜è®¤ 1400pxã€‚æ¨èå€¼ï¼š100%ï¼‰
    inner_max_width: 
    # å¯¼èˆªæ ä¸é¡¶éƒ¨è·ç¦»ï¼ˆtop å’Œ bottom å»ºè®®åªè®¾ç½®å…¶ä¸­ä¸€ä¸ªï¼‰
    top: none
    # å¯¼èˆªæ ä¸åº•éƒ¨è·ç¦»
    bottom: none
    # è‡ªåŠ¨æ”¶èµ·
    auto_folding: true

    # æ‰‹æœºç«¯èœå•ä½ç½®ï¼ˆleftã€rightï¼›é»˜è®¤ leftï¼‰
    mbl_menu: 
    # æ‰‹æœºç«¯èœå•å®½åº¦ï¼ˆmax-content ï¼Œè‡ªåŠ¨ æˆ– px vwï¼Œé»˜è®¤è‡ªåŠ¨ï¼‰
    mbl_outer_width: 
    # æ‰‹æœºç«¯èœå•æŒ‰é’®é«˜åº¦
    mbl_item_height:
    # æ‰‹æœºç«¯èœå•æ°´å¹³å†…é—´è·ï¼ˆé»˜è®¤ 8pxï¼‰
    mbl_horizontal_padding:
    # æ‰‹æœºç«¯èœå•çºµå‘å†…é—´è·ï¼ˆé»˜è®¤ 10pxï¼‰
    mbl_vertical_padding:


    # å…ƒç´ é—´è·ï¼ˆé»˜è®¤ 0pxï¼‰
    item_distance: 
    # å…ƒç´ å†…æ¨ªå‘é—´è·ï¼ˆé»˜è®¤ 8pxï¼‰
    item_inside_distance: 

    # ä¸é€æ˜åº¦ï¼ˆè¾ƒä½çš„èƒŒæ™¯æ¨¡ç³Šåº¦å»ºè®®ä½¿ç”¨è¾ƒé«˜çš„ä¸é€æ˜åº¦ï¼Œè¾ƒä½çš„ä¸é€æ˜åº¦å»ºè®®ä½¿ç”¨è¾ƒé«˜çš„èƒŒæ™¯æ¨¡ç³Šåº¦ã€‚é»˜è®¤ 0.8ï¼‰
    opacity: ''
    # èƒŒæ™¯æ¨¡ç³Šåº¦ï¼ˆå•ä½ï¼špxã€‚å»ºè®®ä¸è¦ä½¿ç”¨è¿‡é«˜çš„æ•°å€¼ï¼Œè¿™å¯èƒ½ä¼šå¯¼è‡´å¡é¡¿ã€‚è®¾ç½® 0 å¯å…³é—­ã€‚ï¼‰
      # ä¸€èˆ¬æƒ…å†µä¸‹ï¼ŒFirefox æµè§ˆå™¨ä¸­ backdrop-filter æœ‰é™åˆ¶
    blur: 
    # å¯¼èˆªæ åœ†è§’ï¼ˆnoneã€defaultã€valueï¼›æ— ã€é»˜è®¤ã€æ•°å€¼ã€‚å»ºè®®ä½¿ç”¨ px è€Œä¸æ˜¯ %ï¼Œä½¿ç”¨ % ä¼šå¯¼è‡´å˜ä¸ºæ¤­åœ†ï¼‰
    border_radius:

    # äºŒçº§èœå•åœ†è§’ï¼ˆé»˜è®¤ 6pxï¼‰
    sub_menu_border_radius:

  # =============================================================
  # ä¾§è¾¹æ 
  sidebar:
    enable: true
    # è‡ªå®šä¹‰ç»„ä»¶ï¼ˆå…è®¸è‡ªç”±è°ƒæ•´é¡ºåºï¼‰
    items:
      pc, 0:
        title: æ ‡é¢˜ï¼ˆå¯å¡«å¯ä¸å¡«ï¼‰
        icon: fas fa-bullhorn, red
        text: <div class="custom_sidebar_object" style="color:red;">
          å¯ä½¿ç”¨ html + css è¯­æ³•
          æ¢è¡Œå¯ä»¥ï¼Œæ³¨æ„ç¼©è¿›
          css ä¸èƒ½ç”¨\<style\>æ ‡ç­¾ï¼Œä¼šæŠ¥é”™
          </div>
        button, 1: /about/, å…³äº, none
        button, 0: /about/, å…³äº, fa fa-heart
        # æ–‡ç« æ•°ç›®
        num_of_articles: è¿™ç§ä¸éœ€è¦å†™ true ä¹‹ç±»çš„ï¼Œä¸€æ—¦å†™äº†å°±ä¼šæŒ‰ç…§è¿™ä¸ªé¡ºåºç”Ÿæˆå‡ºæ¥
        # æ€»å­—æ•°
        total_word_count: 
        # æ€»è®¿å®¢æ•°
        total_visitors: 
        # æ€»è®¿é—®é‡
        total_visits:
        # è¿è¡Œæ—¶é•¿
        runtime:
        # æœ€åæ›´æ–°æ—¶é—´
        last_update:
        # ç¤¾äº¤é“¾æ¥
        social_link, 0: æ­¤å¤„æ€ä¹ˆå†™éƒ½ä¸ä¼šäº§ç”Ÿä»»ä½•æ•ˆæœ
        avatar, 0: round
        avatar, 1: 
        author_name, 0: é»˜è®¤ä½¿ç”¨ç«™ç‚¹é…ç½®æ–‡ä»¶çš„ï¼Œä¹Ÿå¯ä»¥ä¿®æ”¹
        newest_posts, 0:
        tags, 0:
        categories, 0:
      mbl, 0:
        button, 1: /about/, å…³äº, none
      al, 0:
        text: <div class="custom_sidebar_object" style="color:red;">
          å¯ä½¿ç”¨ html + css è¯­æ³•
          æ¢è¡Œå¯ä»¥ï¼Œæ³¨æ„ç¼©è¿›
          css ä¸èƒ½ç”¨\<style\>æ ‡ç­¾ï¼Œä¼šæŠ¥é”™
          </div>
        act_statistics:
          archive: /archives/
          categorie: /categories/
          tag: /tags/
      al, 1:
        toc:
          post: true
          page: true
          list_number: true
  
  # =============================================================
  # é¦–é¡µæ–‡ç« 
  index_posts:
    # å°é¢é»˜è®¤æ ·å¼ã€falseã€sideã€downï¼›å…³é—­ã€ä¾§è¾¹ï¼ˆæ‰‹æœºä¸Šå°†æ˜¾ç¤ºåœ¨ä¸Šæ–¹ï¼‰ã€æ–‡ç« ä¿¡æ¯ä¸‹å±‚ã€‘ï¼ˆæœªå®Œæˆï¼‰
    cover_default_style: side
    # å°é¢ä½ç½®ï¼ˆbothã€leftã€rightã€‚å½“ cover_default_style ä¸º side æ—¶æœ‰æ•ˆï¼‰ï¼ˆæœªé…ç½®ï¼‰
    position:
    # å°é¢é«˜åº¦ï¼ˆå•ä½ï¼špxã€‚å½“ cover_default_style ä¸º top æˆ– down æ—¶æœ‰æ•ˆï¼‰ï¼ˆæœªé…ç½®ï¼‰
    top_default_height:
    
    # ä¿¡æ¯æ ·å¼ï¼ˆfalseã€gradientã€blockï¼›æ— ã€æ¸å˜ã€å—çŠ¶ã€‚å½“ cover_default_style ä¸º down æ—¶æœ‰æ•ˆï¼‰ï¼ˆæœªé…ç½®ï¼‰
    incard_info_bg:
    # block èƒŒæ™¯æ ·å¼ï¼ˆæœªé…ç½®ï¼‰
    incard_info_bg_block:
      # ä¸é€æ˜åº¦ï¼ˆé»˜è®¤ .2ï¼‰ï¼ˆæœªé…ç½®ï¼‰
      opacity: ''
      # ä¸é€æ˜åº¦ï¼ˆé»˜è®¤ 10pxï¼‰ï¼ˆæœªé…ç½®ï¼‰
      blur: 
    # gradient èƒŒæ™¯æ ·å¼ï¼ˆæœªé…ç½®ï¼‰
    incard_info_bg_gradient:
      # å¼€å§‹å’Œç»“æŸé¢œè‰²ï¼ˆè‰²å€¼å¿…é¡»ç”¨è‹±æ–‡å¼•å·åŒ…æ‹¬ï¼Œä¾‹ï¼š'#2333'ï¼‰ï¼ˆæœªé…ç½®ï¼‰
      begin_color: ''
      end_color: ''
    
    # æ–‡ç« æ¦‚è¦ã€æè¿°
    description:
      # ç±»å‹ã€falseã€descriptionã€excerptã€contentã€autoï¼›å…³é—­ã€æè¿°ã€æ¦‚è¦ã€é€‰å–æ–‡ç« å†…å®¹ã€è‡ªåŠ¨ï¼ˆä¼˜å…ˆçº§ï¼šæè¿° > æ¦‚è¦ > æ–‡ç« å†…å®¹ï¼‰ã€‘ï¼ˆæœªé…ç½®ï¼‰
      type:
      # æ— æ¦‚è¦ã€æè¿°æ—¶æ˜¾ç¤ºï¼ˆå½“ type ä¸º description æˆ– excerpt æ—¶æœ‰æ•ˆï¼‰ï¼ˆæœªé…ç½®ï¼‰
      default_description:
      # æœ€å¤§é•¿åº¦ï¼ˆå½“ type ä¸º content æˆ– auto æ—¶æœ‰æ•ˆï¼Œæ¨èä¸å¤§äº500ï¼‰
      max_length: 300
    # å­—æ•°ç»Ÿè®¡
    wordcount: true

  # =============================================================
  # é¡µé¢æ ·å¼
  page:
    # ä¿¡æ¯æ ·å¼ï¼ˆfalseã€gradientã€blockï¼›æ— ã€æ¸å˜ã€å—çŠ¶ã€‚ï¼‰
    incard_info_bg: gradient
    # block èƒŒæ™¯æ ·å¼
    incard_info_bg_block:
      # ä¸é€æ˜åº¦ï¼ˆé»˜è®¤ .8ï¼‰
      opacity: ''
      # ä¸é€æ˜åº¦ï¼ˆé»˜è®¤ 10pxï¼‰
      blur: 
    # gradient èƒŒæ™¯æ ·å¼
    incard_info_bg_gradient:
      # å¼€å§‹å’Œç»“æŸé¢œè‰²ï¼ˆè‰²å€¼å¿…é¡»ç”¨è‹±æ–‡å¼•å·åŒ…æ‹¬ï¼Œä¾‹ï¼š'#2333'ï¼‰
      begin_color: ''
      end_color: ''
    
    # é¡µé¢èƒŒæ™¯åŒæ–‡ç« å°é¢ï¼ˆæœªé…ç½®ï¼‰
    bg_as_cover:

    # æ®µè½æ ‡é¢˜æ˜“è¯»æ€§å¢å¼º
    paragraph_title_readability: true
    # å°† H2 æ˜¾ç¤ºä¸º H1ï¼Œä»¥æ­¤ç±»æ¨ï¼Œç”¨äºä¼˜åŒ– SEO åä¾¿äºé˜…è¯»ï¼ˆæœªé…ç½®ï¼‰
    after_seo_paraTitleReadly: false

    # ä»£ç é«˜äº®æ ·å¼ï¼ˆæœªé…ç½®ï¼Œå°†å…è®¸ç”¨æˆ·æ’å…¥è‡ªå·±åœ¨ highlightjs é€‰æ‹©çš„æ ·å¼ï¼‰ï¼ˆæœªé…ç½®ï¼‰
    code_highlight_style:
      light:
      dark:
    # å¤åˆ¶æŒ‰é’®
    copy_button: true
    # è‡ªåŠ¨æ¢è¡Œï¼ˆæœªé…ç½®ï¼‰
    auto_warp:
    # æŠ˜å æŒ‰é’®ï¼ˆæœªé…ç½®ï¼‰
    # æŠ˜å ï¼ˆé»˜è®¤æŠ˜å ã€è¶…è¿‡é•¿åº¦éšè—ï¼‰ï¼ˆæœªé…ç½®ï¼‰

    # å›¾ç‰‡æè¿°æ–‡å­—
    img_desc: true

    # ç‰ˆæƒä¿¡æ¯

    # å­—æ•°ç»Ÿè®¡
    wordcount: true
  
  # å‹é“¾æ ·å¼
  link:
    # å¤´åƒåœ†è§’ï¼ˆroundã€squareã€autoï¼›åœ†ã€æ–¹å½¢ã€è‡ªåŠ¨ï¼‰
    avatar_radius: round
    # å°†å†…å®¹æ¸²æŸ“åˆ°åˆ†ç±»ä¹‹å
    after_content: true

  # =============================================================
  # é¡µè„š
  footer:
    since: 2020
    # è¿è¡Œæ—¶é•¿
    runtime: true
    # ç‰ˆæƒä¿¡æ¯
    copyright: true
    # è‡ªå®šä¹‰ä¿¡æ¯
    content: <span>âœ¨ </span><span style="color:white;">hello</span><span> there! </span><span>This content work with css!</span><span> ğŸ‰</span>
      <br>
      <span>âœ¨ </span><span style="color:white;">ä½ </span><span>å¥½ï¼</span><span>è¿™æ®µæ–‡æœ¬ä½¿ç”¨äº† CSSï¼</span><span> ğŸ‰</span>

  # =============================================================
  # å…¨å±€
  
  # ä¸»é¢˜è‰²
  theme_color:
    main: "#009688"

    # è‰²ç›¸é…è‰²ï¼ˆ0~360ã€falseï¼›é€‰æ‹©è‰²ç›¸ã€å…³é—­ã€‚ç”±ä¸»é¢˜æ ¹æ®è‰²ç›¸è°ƒæ•´é¢œè‰²ï¼‰ï¼ˆæœªå®Œæˆï¼‰*
    hue: false

    # éšæœºè‰²ç›¸ï¼ˆå°†æ— æ³•è‡ªå®šä¹‰ï¼Œæ¯æ¬¡åˆ·æ–°æ›´æ¢é¢œè‰²ï¼‰ï¼ˆæœªå®Œæˆï¼‰*
    random_color: false

    # é»‘ç™½ï¼ˆæœªé…ç½®ï¼‰*
    black_and_white:

  # =============================================================
  # å­—ä½“ï¼ˆæš‚æœªå®Œæˆï¼‰
  font:
    font-family: ''
    font-url: ''

  # =============================================================
  # è‡ªå®šä¹‰èƒŒæ™¯ï¼ˆå‡éµç…§ css è¯­æ³•ï¼‰
  background:
    # ç±»å‹ï¼ˆnoneã€blurã€bg_imgï¼›æ— ã€æœ¦èƒ§ã€è‡ªå®šä¹‰èƒŒæ™¯ï¼‰
    style: blur
    blur:
      # å›¾ç‰‡
      img: 'url(/448.jpg)' # æŒ‰ç…§ css è¯­æ³•
      # è·Ÿéšæ»šåŠ¨
      scroll: false
      # æ¨¡ç³Šåº¦ï¼ˆå•ä½ï¼špxï¼‰
      blur: '20px'
      # ä¸é€æ˜åº¦
      opacity: '.3'
    bg_img: '' # æŒ‰ç…§ css è¯­æ³•ï¼Œä½œç”¨äº background-image


  # =============================================================
  # ä¸»é¡µæ¨ªå¹…å›¾åƒ
  index_banner_img: 'url(/448.jpg)'
  # ä¸»é¡µæ¨ªå¹…é«˜åº¦ï¼ˆå•ä½ï¼špxã€vhï¼‰
  index_banner_height: 
  # æ»šåŠ¨è§†å·®
  index_banner_img_parallax: true
  # ä¸»é¡µå¤§æ ‡é¢˜å­—ä½“å¤§å°åŸºæ•°ï¼ˆé»˜è®¤ 96pxï¼‰
  index_big_title_font_size:
  # ä¸»é¡µå‰¯æ ‡é¢˜å­—ä½“å¤§å°åŸºæ•°ï¼ˆé»˜è®¤ 24pxï¼‰
  index_subtitle_font_size:

  # =============================================================
  # æ¿å—å¤–è¾¹æ¡†ï¼ˆå•ä½ï¼špxï¼‰
  block-margin: 
  # æ¿å—å†…è¾¹æ¡†
  block-padding: 
  # æ¨¡å—åœ†è§’ï¼ˆå•ä½ï¼špxï¼‰
  border-radius:
  # æ¨¡å—èƒŒæ™¯ä¸é€æ˜åº¦ï¼ˆè¾ƒä½çš„èƒŒæ™¯æ¨¡ç³Šåº¦å»ºè®®ä½¿ç”¨è¾ƒé«˜çš„ä¸é€æ˜åº¦ï¼Œè¾ƒä½çš„ä¸é€æ˜åº¦å»ºè®®ä½¿ç”¨è¾ƒé«˜çš„èƒŒæ™¯æ¨¡ç³Šåº¦ï¼‰
  global-opacity: ''
  # æ¨¡å—èƒŒæ™¯é«˜æ–¯æ¨¡ç³Šåº¦ï¼ˆå•ä½ï¼špxã€‚å»ºè®®ä¸è¦ä½¿ç”¨è¿‡é«˜çš„æ•°å€¼ï¼Œè¿™å¯èƒ½ä¼šå¯¼è‡´å¡é¡¿ã€‚è®¾ç½® 0 å¯å…³é—­ã€‚ï¼‰
  global-blur: 0
  # æœ€å¤§å®½åº¦ï¼ˆå•ä½ï¼špxã€‚é»˜è®¤ï¼š1400pxã€‚å»ºè®®å¤§äº 1000px è¿‡å°çš„å€¼ä¼šå¯¼è‡´æ’ç‰ˆé”™ä¹±ã€‚è®¾ç½®ä¸º none å…³é—­ã€‚ï¼‰
  max-width: 
  # æœ€å°è¾¹ç•Œï¼ˆå½“å±å¹•å®½åº¦å°äºæœ€å¤§å®½åº¦æ—¶ï¼Œé»˜è®¤ 16pxï¼‰
  min_margin:

  # =============================================================
  # è½¬è·³åˆ°å†…å®¹æŒ‰é’®ï¼ˆè¿›å…¥é¡µé¢åæŒ‰ä¸‹ Tabï¼Œå°†ä¼šåœ¨å±å¹•é¡¶éƒ¨å‡ºç°æ­¤æŒ‰é’®ï¼‰
  skip_to_content_buttom: true
  # åœ¨é€‚å½“çš„åŒºåŸŸå¢åŠ è¿”å›æŒ‰é’®
  back_buttom: true
  # é¡µé¢åˆ‡æ¢æŒ‰é’®æ ·å¼ï¼ˆflex-startã€flex-endã€centerï¼›å±…å·¦ã€å±…å³ã€å±…ä¸­ã€‚é»˜è®¤å±…ä¸­ï¼‰
  page_switch_btn_style: 

  # å…è®¸æ”¾å¤§ï¼ˆåŒæŒ‡æ”¾å¤§ï¼‰
  user_scalable: true
  # æ–‡ç« å¤–ç¦ç”¨é€‰ä¸­ï¼ˆæœªé…ç½®ï¼‰*
  no_select_unless_article: true
  # æ–‡ç« ç¦ç”¨é€‰ä¸­ï¼ˆæœªé…ç½®ï¼‰*
  no_select_in_article: false

  # åŠ¨ç”»æ•ˆæœï¼ˆfalseã€slowã€normalã€fastï¼›å…³é—­ã€æ…¢ã€ä¸­ç­‰ã€å¿«ï¼‰ï¼ˆæœªé…ç½®ï¼‰
  animation:

# =============================================================
# ç¬¬ä¸‰æ–¹
third_party:
  # busuanzi ç»Ÿè®¡ï¼ˆå¼•å…¥ js ç”¨äºç»Ÿè®¡è®¿é—®é‡ä¸è®¿å®¢æ•°ï¼‰
  busuanzi: true

# =============================================================
CDN:
  # ä¸»è¦å¼•å…¥ Mainly introduced
  mainCss: /css/hexo-theme-apha.css
  mainJs: /js/hexo-theme-apha.js

  fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css

  busuanzi: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

  # highlightjs_css: 
  # highlightjs_js: //unpkg.com/@highlightjs/cdn-assets@11.4.0/highlight.min.js

  # highlight_js_css: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/styles/default.min.css
  # highlight_js_js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.3.1/build/highlight.min.js